//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBooksDatatable
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksTable
    {
        public string BookID { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public string Year { get; set; }
        public string Genre { get; set; }
        public string Page { get; set; }
        public string Price { get; set; }
        public string Country { get; set; }
    }
}
